enum KeyMap {
    static func char(for keyCode: Int64) -> String {
        switch keyCode {
        case 0:  return "a"
        case 1:  return "s"
        case 2:  return "d"
        case 3:  return "f"
        case 4:  return "h"
        case 5:  return "g"
        case 6:  return "z"
        case 7:  return "x"
        case 8:  return "c"
        case 9:  return "v"
        case 11: return "b"
        case 12: return "q"
        case 13: return "w"
        case 14: return "e"
        case 15: return "r"
        case 16: return "y"
        case 17: return "t"
        case 31: return "o"
        case 32: return "u"
        case 34: return "i"
        case 35: return "p"
        case 37: return "l"
        case 38: return "j"
        case 40: return "k"
        case 45: return "n"
        case 46: return "m"
        case 18: return "1"
        case 19: return "2"
        case 20: return "3"
        case 21: return "4"
        case 23: return "5"
        case 22: return "6"
        case 26: return "7"
        case 28: return "8"
        case 25: return "9"
        case 29: return "0"
        case 27: return "-"
        case 24: return "="
        case 33: return "["
        case 30: return "]"
        case 41: return ";"
        case 39: return "'"
        case 43: return ","
        case 47: return "."
        case 44: return "/"
        case 49: return " "
        case 53: return "\u{1B}"
        default: return ""
        }
    }
}
